### ISSUE TITLE
move folder?

### ISSUE THREAD

**Issue by liocarcinus** [ices-eg/WKSSFGEO#7]
I think that 'code_example
Create Identifying fishing trips.Rmd' should be within r-dev, according to what we spoke, no?

´'define_trips.R' is the same as define_trips_pol.r? if so should we remove the first one?

:D 
Cheers,
M.

**Comment by einarhjorleifsson** [comment]
yes to the first question - actually for all i care it can be deleted.
on the other question @jepol77 knows that stuff.

**Comment by jepol77** [comment]
Looks like define_trips.R is another approach - maybe just rename it? Think its fine to have different approaches for the same functions.

**Comment by liocarcinus** [comment]
After thinking a little about this, perhaps we should implement that every function / script should have the initials of who produced it in the name and on a heading. Does this make sense to you?

**Comment by einarhjorleifsson** [comment]
think this can be closed
